## Path to sample sheet
samplesheet: 'samplesheet.txt'

## List columns to group (i.e. any columns left out will become part of the same group)
groupBy: ['Project', 'Cell_Type', 'Genotype', 'Time', 'Bio_Rep', 'Tech_Rep']

## Genome-specific reference parameters
fasta: '/proj/seq/data/hg38_UCSC/Sequence/BWAIndex/genome.fa' 
chromSizes: '/proj/phanstiel_lab/References/chromSizes/hg38_chromSizes.txt'

## Restriction site information
site: "MboI" # or 'none'
site_file: 'restriction_sites/hg38_MboI.txt' # Make sure chromosomes match bwa index chromosomes (i.e. both start with "chr")
ligation: "GATCGATC"

## Set splitsize
splitsize: 200000000 ## 200000000 good default (50M reads/file) (i.e. 4000000 = 1M reads/file) 

## Java memory for buildHiC (hic/norm rules)
javaMem: "250880"

## Additional options
mapq0_reads_included: 0
